# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cFullName', models.CharField(max_length=250)),
                ('cShortName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fFullName', models.CharField(max_length=250)),
                ('fShortName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('idGroup', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('yearOfBegin', models.DateField()),
                ('gCafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cafedra')),
                ('gFaculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lDate', models.DateField()),
                ('lName', models.CharField(max_length=250)),
                ('lTime', models.CharField(max_length=45)),
                ('lAud', models.CharField(max_length=45, verbose_name='Auditorium')),
                ('lGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(max_length=100)),
                ('tEmail', models.EmailField(max_length=254)),
                ('tCafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cafedra')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='lTeacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher'),
        ),
        migrations.AddField(
            model_name='cafedra',
            name='cFaculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Faculty'),
        ),
    ]
