# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='gCafedra',
        ),
        migrations.AlterField(
            model_name='cafedra',
            name='cFaculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='cafedra',
            name='cFullName',
            field=models.CharField(max_length=250, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='cafedra',
            name='cShortName',
            field=models.CharField(max_length=45, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fFullName',
            field=models.CharField(max_length=250, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fShortName',
            field=models.CharField(max_length=45, verbose_name='Сокращенное название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='gFaculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='group',
            name='idGroup',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='yearOfBegin',
            field=models.DateField(verbose_name='Год начала обучения'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lAud',
            field=models.CharField(max_length=45, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tCafedra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cafedra', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tEmail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tName',
            field=models.CharField(max_length=100, verbose_name='ФИО преподавателя'),
        ),
    ]
