# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170518_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tDegree',
            field=models.CharField(blank=True, max_length=45, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tTitle',
            field=models.CharField(blank=True, max_length=45, verbose_name='Ученое звание'),
        ),
    ]
