# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170525_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tDegree',
            field=models.CharField(blank=True, default='не указана', max_length=45, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tEmail',
            field=models.EmailField(blank=True, default='не указан', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tTitle',
            field=models.CharField(blank=True, default='не указана', max_length=45, verbose_name='Должность'),
        ),
    ]
